# Dockerfile to run tests for a file called submission.js, which will be in the same directory as this Dockerfile
# It should also copy

# Use the latest node image
FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# RUN npm install

# Run tests
CMD [ "npm", "test" ]
